import ContadorApp from './components/Counter'
import Navegacion from './components/Navegacion'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navegacion/>
      <body className={inter.className}>{children}</body>
      <ContadorApp/>
    </html>
  )
}
